import time 
name = input("what your name: ")
print("hello " + name)
birthyear = input("what is your birthyear ")
age = (2023 - int(birthyear))
print("age")
print("loading info ...")
time.sleep(5)
print("info:") 
print("name:")
print(name)
print("age:")
print(age)
print("regestierd")