name = input("what is your name? ")
print("hello " + name)
birth_year = input("enter birth year: ") 
age = 2022 - int(birth_year)
print(age)
print("info")
print("name: ")
print(name)
print("age: ") 
print(age)
print("you are registed " + name)
